new post pathway created to add new comment
DJHymers/be-nc-games pull request #5
Opened 2023-03-30 15:32 UTC by DJHymers

2023-03-30 15:39 UTC, robert112233 requested changes
Write the missing tests then submit another PR for review, nice work 👍

2023-03-30 15:39 UTC, robert112233 commented on __tests__/app.test.js
> +  });
It's still worth testing the usual errors here, 400 invalid review ID,  404 review ID not found etc. 

You should also include a test for 404 invalid username {username: "aUserThat IsntInTheDatabase", body : "validComment"}

2023-03-31 07:57 UTC, RichardNeat approved these changes
Nice one David, just one minor change I've mentioned below then feel free to merge :)

2023-03-31 07:57 UTC, RichardNeat commented on __tests__/app.test.js
> +    it("400: invalid username provided, should provide bad path message", () => {
a 404 would be more appropriate here as the request isn't 'bad' necessarily it's just that it doesn't exist.

2023-03-31 09:12 UTC, merged